---

- name: Stop tomcat
  service:
    name: "{{ tomcat_service }}"
    state: stopped
    pattern: "{{ tomcat_service }}"

- name: Create release directory
  file:
    path: "{{ releases_folder }}"
    state: directory

- name: Download liquibase-runner-{{ version }}.zip
  get_url:
    url: https://build-inera.nordicmedtest.se/nexus/repository/{{ repo }}/se/inera/privatlakarportal/privatlakarportal-liquibase-runner/{{ version }}/privatlakarportal-liquibase-runner-{{ version }}.zip
    dest: "{{ releases_folder }}/privatlakarportal-liquibase-runner-{{ version }}.zip"
  when: deploy_from_repo|bool

- name: Copy privatlakarportal-liquibase-runner-{{ version }}.zip
  copy:
    src: "{{ playbook_dir }}/../tools/liquibase-runner/build/distributions/privatlakarportal-liquibase-runner-{{ version }}.zip"
    dest: "{{ releases_folder }}/privatlakarportal-liquibase-runner-{{ version }}.zip"
  when: not deploy_from_repo|bool

- name: Unzip liquibase-runner-{{ version }}.zip
  unarchive:
    src: "{{ releases_folder }}/privatlakarportal-liquibase-runner-{{ version }}.zip"
    dest: "{{ releases_folder }}"
    creates: "{{ releases_folder }}/privatlakarportal-liquibase-runner-{{ version }}/bin/liquibase-runner"
    remote_src: yes

- name: Run liquibase update
  command: "{{ releases_folder }}/privatlakarportal-liquibase-runner-{{ version }}/bin/privatlakarportal-liquibase-runner --url={{ database_url }} --username={{ database_username }} --password={{ database_password }} update"
  args:
      chdir: "{{ releases_folder }}/privatlakarportal-liquibase-runner-{{ version }}"
  environment:
      JAVA_HOME: "{{ java_home }}"

- name: Download privatlakarportal-web-{{ version }}.war
  get_url:
    url: "https://build-inera.nordicmedtest.se/nexus/repository/{{ repo }}/se/inera/privatlakarportal/privatlakarportal-web/{{ version }}/privatlakarportal-web-{{ version }}.war"
    dest: "{{ releases_folder }}/privatlakarportal-web-{{ version }}.war"
  when: deploy_from_repo|bool

- name: Copy privatlakarportal-web-{{ version }}.war
  copy:
    src: "{{ playbook_dir }}/../web/build/libs/privatlakarportal-web-{{ version }}.war"
    dest: "{{ releases_folder }}/privatlakarportal-web-{{ version }}.war"
  when: not deploy_from_repo|bool

- name: Remove old version of unpacked privatlakarportal war
  file:
    state: absent
    path: "{{ webapps_folder }}/ROOT"

- name: Deploy privatlakarportal-web-{{ version }}.war as ROOT.war in {{ webapps_folder }}
  copy:
    src: "{{ releases_folder }}/privatlakarportal-web-{{ version }}.war"
    dest: "{{ webapps_folder }}/ROOT.war"
    remote_src: True

- name: Remove privatlakarportal-liquibase-runner-{{ version }}.zip from releases
  file:
    state: absent
    path: "{{ releases_folder }}/privatlakarportal-liquibase-runner-{{ version }}.zip"

- name: Remove privatlakarportal-web-{{ version }}.war from releases
  file:
    state: absent
    path: "{{ releases_folder }}/privatlakarportal-web-{{ version }}.war"

- name: Create version file
  template:
    src: version.txt.j2
    dest: "{{ webapps_folder }}/version.txt"

- name: Update configuration to {{ config_version }}
  git:
    repo: "{{ config_repository }}"
    dest: "{{ config_folder }}"
    version: "{{ config_version }}"

- name: Start tomcat
  service:
    name: "{{ tomcat_service }}"
    state: restarted
    pattern: "{{ tomcat_service }}"
