---
# file: roles/privatlakarportal-resurser/tasks/main.yml

- name: configure shared jdbc datasource for Privatlakarportal
  lineinfile:
    dest="{{ tomcat_conf }}/server.xml"
    regexp="    <Resource name='sharedPrivatlakarportal'"
    insertbefore="  </GlobalNamingResources>"
    line="    <Resource name='sharedPrivatlakarportal' global='sharedPrivatportal' type='javax.sql.DataSource' factory='org.apache.tomcat.jdbc.pool.DataSourceFactory' username='{{ database_username }}' password='{{ database_password }}' driverClassName='{{ database_driver }}' url='{{ database_url }}' maxActive='{{ database_pool_maxActive }}' maxIdle='{{ database_pool_maxIdle }}' minIdle='{{ database_pool_minIdle }}' initialSize='{{ database_pool_initialSize }}' validationQuery='SELECT 1' validationQueryTimeout='3' testWhileIdle='true' timeBetweenEvictionRunsMillis='300000' minEvictableIdleTimeMillis='60000' defaultAutocommit='false' logAbandoned='true'/>"

- name: configure jdbc resource
  lineinfile:
    dest="{{ tomcat_conf }}/context.xml"
    regexp="    <ResourceLink name='jdbc/privatlakarportal'"
    insertbefore="</Context>"
    line="    <ResourceLink name='jdbc/privatlakarportal' global='sharedPrivatlakarportal' type='javax.sql.DataSource'/>"
