apiVersion: v1
data:
  CGI_ELEG_SAML_KEYSTORE_ALIAS: verifiering.registrering.intygstjanster.sjunet.org
  CGI_ELEG_SAML_KEYSTORE_FILE: file://${certificate.folder}/verifiering.registrering.intygstjanster.sjunet.org.jks
  DB_NAME: ${database.name}
  DB_PORT: "3306"
  DB_SERVER: 10.252.5.13
  HSA_WS_CERTIFICATE_FILE: ${certificate.folder}/verifiering.registrering.intygstjanster.sjunet.org.p12
  HSA_WS_CERTIFICATE_TYPE: PKCS12
  HSA_WS_SERVICE_LOGICALADDRESS: unused
  HSA_WS_SERVICES_URL: https://wstest.hsa.sjunet.org/svr-hsaws2/hsaws
  HSA_WS_TRUSTSTORE_FILE: ${certificate.folder}/truststore.jks
  HSA_WS_TRUSTSTORE_TYPE: JKS
  MAIL_HOST: mailout.sth.basefarm.net
  NTJP_BASE_URL: https://qa.esb.ntjp.se/vp
  NTJP_WS_CERTIFICATE_FILE: ${certificate.folder}/verifiering.registrering.intygstjanster.sjunet.org.p12
  NTJP_WS_CERTIFICATE_TYPE: PKCS12
  NTJP_WS_TRUSTSTORE_FILE: ${certificate.folder}/truststore.jks
  NTJP_WS_TRUSTSTORE_TYPE: JKS
  PRIVATLAKARPORTAL_HOST_URL: https://verifiering.registrering.intygstjanster.se
  PUTJANST_LOGICALADDRESS: SE165565594230-1000
  REDIS_HOST: ind-sint-redis1.ind1.sth.basefarm.net;ind-sint-redis2.ind1.sth.basefarm.net;ind-sint-redis3.ind1.sth.basefarm.net
  REDIS_PORT: 26379;26379;26379
  REDIS_SENTINEL_MASTER_NAME: ind-sint-redis
  REFDATA_URL: file://localhost/opt/privatlakarportal/env/refdata-1.0.0.66.jar
  RESOURCES_FOLDER: 'classpath:'
  SPRING_PROFILES_ACTIVE: qa,pp-security-test,caching-enabled,redis-sentinel
  WEBCERT_HOST_URL: https://verifiering.webcert.intygstjanster.se
  WEBCERT_INTERNAL_HOST_URL: http://webcert:8080/services
  WEBCERT_WS_TRUSTSTORE_FILE: ${certificate.folder}/truststore.jks
  WEBCERT_WS_TRUSTSTORE_TYPE: JKS
kind: ConfigMap
metadata:
  creationTimestamp: 2019-04-01T10:09:35Z
  name: privatlakarportal-configmap-envvar
  namespace: sintyg
  resourceVersion: "71677692"
  selfLink: /api/v1/namespaces/sintyg/configmaps/privatlakarportal-configmap-envvar
  uid: 405d736d-5466-11e9-8635-005056a1b955
