apiVersion: v1
data:
  DB_USERNAME: "<value>"
  DB_PASSWORD: "<value>"
  REDIS_PASSWORD: "<value>"
  MAIL_USERNAME: "<value>"
  MAIL_PASSWORD: "<value>"
  CGI_ELEG_SAML_KEYSTORE_PASSWORD: "<value>"
  HSA_WS_CERTIFICATE_PASSWORD: "<value>"
  HSA_WS_KEY_MANAGER_PASSWORD: "<value>"
  HSA_WS_TRUSTSTORE_PASSWORD: "<value>"
  NTJP_WS_CERTIFICATE_PASSWORD: "<value>"
  NTJP_WS_KEY_MANAGER_PASSWORD: "<value>"
  NTJP_WS_TRUSTSTORE_PASSWORD: "<value>"
  WEBCERT_WS_TRUSTSTORE_PASSWORD: "<value>"
kind: Secret
metadata:
  name: privatlakarportal-stage-secret-envvar
type: Opaque
