apiVersion: v1
stringData:
  DB_USERNAME: "privatlakarportal"
  DB_PASSWORD: ""
  REDIS_PASSWORD: ""
  MAIL_USERNAME: "unused"
  MAIL_PASSWORD: ""
  CGI_ELEG_SAML_KEYSTORE_PASSWORD: ""
  HSA_WS_CERTIFICATE_PASSWORD: ""
  HSA_WS_KEY_MANAGER_PASSWORD: ""
  HSA_WS_TRUSTSTORE_PASSWORD: ""
  NTJP_WS_CERTIFICATE_PASSWORD: ""
  NTJP_WS_KEY_MANAGER_PASSWORD: ""
  NTJP_WS_TRUSTSTORE_PASSWORD: ""
  WEBCERT_WS_TRUSTSTORE_PASSWORD: ""
kind: Secret
metadata:
  name: privatlakarportal-secret-envvar
type: Opaque
