# This playbook deploys privatlakarportalen 

- hosts: tomcat
  serial: 1
  become: yes
  vars:
    # repo - values: 'snapshots or 'releases'
    repo: snapshots
    version: 1.0.0-SNAPSHOT
    config_version: master

  roles:
    - app-resources
    - privatlakarportal
