---

- hosts: tomcat
  serial: 1
  become: yes
  environment:
    "{{ proxy_env }}"
  vars:
    # repo - values: 'snapshots or 'releases'
    repo: releases
    config_version: master

  roles:
    - app-resources
    - privatlakarportal
