---

- hosts: tomcat
  serial: 1
  become: yes
  environment:
    "{{ proxy_env }}"
  roles:
    - privatlakarportal-systemvariabler
    - privatlakarportal-resurser
    - privatlakarportal-jarfiler
    - config-folder
