---
# This playbook provisions Tomcat resources for Privatlakarportalen 

- hosts: tomcat
  serial: 1
  become: yes

  roles:
    - privatlakarportal-systemvariabler
    - privatlakarportal-resurser
    - privatlakarportal-jarfiler
    - config-folder
