---

- name: Check if {{ tomcat_service }} exists
  stat:
    path: "/etc/init.d/{{ tomcat_service }}"
  register: service_status

- name: ... and Stop {{ tomcat_service }} if it does
  service:
    name: "{{ tomcat_service }}"
    state: stopped
    pattern: "{{ tomcat_service }}"
  when: service_status.stat.exists
  register: service_stopped
